FROM trafex/php-nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --chmod=644 server.key /etc/nginx/ssl/server.key
COPY server.crt /etc/nginx/ssl/server.crt
COPY pk-passphrase /etc/nginx/ssl/pk-passphrase
