FROM php:8-apache

COPY demo.conf /etc/apache2/sites-available/demo.conf
COPY server.crt /etc/apache2/ssl/server.crt
COPY server.key /etc/apache2/ssl/server.key
COPY pk-passphrase-provider.sh /etc/apache2/ssl/passphrase.sh
COPY ssl-passphrase.conf /etc/apache2/conf-available/ssl-passphrase.conf

RUN a2enmod ssl && a2enconf ssl-passphrase && a2ensite demo.conf && a2dissite 000-default.conf
