version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: ssl-test-apache
    hostname: localhost
    ports:
      - "2345:80"
      - "3456:443"
    volumes:
      - "./html:/var/www/html"
