#!/usr/bin/env bash

# Takes a domain name and two port numbers, and applies those
# settings to the files needed to run a containerized Apache web server.

if [[ $# -lt 2 || $# -gt 3 ]]; then
    printf "\nUsage:  $0 <HTTP port> <HTTPS port> [<domain name>]\n\n"
    exit 0
fi

if [ $# -eq 2 ]; then
    DOMAIN=$HOSTNAME
    if [ -z $HOSTNAME ]; then
        echo "You didn't provide a domain name, and your machine doesn't have one either"
        exit 1
    fi
else
    DOMAIN=$3
fi

FILE=docker-compose.yml
echo "Inserting domain name '$DOMAIN' into $FILE"
sed -i "s/\(hostname\s*:\)\s*.*/\1 $DOMAIN/" $FILE
echo "Inserting HTTP port numbers $1 and $2 into $FILE"
sed -i "s/\"[[:digit:]]\+:80\"/\"$1:80\"/" $FILE
sed -i "s/\"[[:digit:]]\+:443\"/\"$2:443\"/" $FILE

FILE=server.conf
echo "Inserting domain name '$DOMAIN' into $FILE"
sed -i "s/\(ServerName\)\s*.*/\1 $DOMAIN/" $FILE
sed -i "s/\(ServerAdmin\)\s*.*/\1 admin@$DOMAIN/" $FILE

FILE=html/index.html
echo "Inserting domain name '$DOMAIN' into the header text of $FILE"
sed -i "s/<h1>.*<\/h1>/<h1>Welcome to $DOMAIN<\/h1>/" $FILE
echo "Inserting domain name '$DOMAIN' and HTTP port number $1 into $FILE"
sed -i "s/http:\/\/[^/]*/http:\/\/$DOMAIN:$1/" $FILE
echo "Inserting domain name '$DOMAIN' and HTTPS port number $2 into $FILE"
sed -i "s/https:\/\/[^/]*/https:\/\/$DOMAIN:$2/" $FILE

FILE=ssl-passphrase.conf
echo "Inserting domain name '$DOMAIN' into $FILE"
sed -i "s/\(ServerName\)\s\+.*/\1 $DOMAIN/" $FILE
