#!/usr/bin/env bash

# Takes a domain name and two port numbers, and applies those
# settings to the files needed to run a containerized Apache web server.

if [ $# -ne 3 ]; then
    printf "\nUsage:  $0 <domain> <HTTP port> <HTTPS port>\n\n"
    exit 0
fi

FILE=docker-compose.yml
echo "Inserting domain name '$1' into $FILE"
sed -i "s/\(hostname\s*:\)\s*.*/\1 $1/" $FILE
echo "Inserting HTTP port numbers $2 and $3 into $FILE"
sed -i "s/\"[[:digit:]]\+:80\"/\"$2:80\"/" $FILE
sed -i "s/\"[[:digit:]]\+:443\"/\"$3:443\"/" $FILE

FILE=server.conf
echo "Inserting domain name '$1' into $FILE"
sed -i "s/\(ServerName\)\s*.*/\1 $1/" $FILE
sed -i "s/\(ServerAdmin\)\s*.*/\1 admin@$1/" $FILE

FILE=html/index.html
echo "Inserting domain name '$1' into the header text of $FILE"
sed -i "s/<h1>.*<\/h1>/<h1>Welcome to $1<\/h1>/" $FILE
echo "Inserting domain name '$1' and HTTP port number $2 into $FILE"
sed -i "s/http:\/\/[^/]*/http:\/\/$1:$2/" $FILE
echo "Inserting domain name '$1' and HTTPS port number $3 into $FILE"
sed -i "s/https:\/\/[^/]*/https:\/\/$1:$3/" $FILE

FILE=ssl-passphrase.conf
echo "Inserting domain name '$1' into $FILE"
sed -i "s/\(ServerName\)\s\+.*/\1 $1/" $FILE
