#!/usr/bin/env bash

# Takes a domain name and
# - creates a private key plus a signed certificate for server deployment;
# - saves the passphrase you supply in a file for deployment on Apache;
# - creates an Apache server configuration file.

if [ $# -ne 1 ]; then
    echo "  Usage:  $0 <domain>"
    exit 0
fi

DOMAIN=$1
CA_KEY_FILE=ca-root.key
CA_CRT_FILE=ca-root.crt
CA_PASSPHRASE_FILE=ca-passphrase
SERVER_KEY_FILE=server.key
SERVER_REQ_FILE=server.csr
SERVER_CRT_FILE=server.crt
SERVER_PASSPHRASE_FILE=pk-passphrase-for-apache.sh

# Check for CA key.
if [ ! -f $CA_KEY_FILE ]; then
    >&2 echo "CA key $CA_KEY_FILE not found"
    exit 1
fi

# Check for CA certificate.
if [ ! -f $CA_CRT_FILE ]; then
    >&2 echo "CA certificate $CA_CRT_FILE not found"
    exit 1
fi

# Check for CA passphrase file.
if [ ! -f $CA_PASSPHRASE_FILE ]; then
    >&2 echo "CA passphrase file $CA_PASSPHRASE_FILE not found"
    exit 1
fi
CA_PASSPHRASE=$(<$CA_PASSPHRASE_FILE)

# Ask for domain passphrase.
read -s -p "Enter passphrase for private key: " PK_PASSPHRASE
echo

# Generate private key.
echo "Generating private key"
openssl genpkey -quiet -algorithm rsa -pass pass:$PK_PASSPHRASE \
-aes256 -out $SERVER_KEY_FILE

# Create a signing request from the private key.
echo "Creating signing request"
openssl req -new -key $SERVER_KEY_FILE -out $SERVER_REQ_FILE \
-passin pass:$PK_PASSPHRASE -subj "/CN=$DOMAIN" \
-addext "subjectAltName=email:admin@$DOMAIN"

# Sign the request with the CA root certificate.
echo "Signing request with root certificate"
openssl x509 -in $SERVER_REQ_FILE -req -CA $CA_CRT_FILE -CAkey $CA_KEY_FILE \
-passin pass:$CA_PASSPHRASE -out $SERVER_CRT_FILE \
-extfile <(printf "authorityKeyIdentifier=keyid,issuer\n
basicConstraints=CA:FALSE\nsubjectAltName=DNS:$DOMAIN")

# Create a passphrase file for Apache.
printf "#!/bin/sh\necho \"$PK_PASSPHRASE\"\n" > $SERVER_PASSPHRASE_FILE
chmod a+x $SERVER_PASSPHRASE_FILE
echo "Passphrase written to $SERVER_PASSPHRASE_FILE"

echo "Removing signing request file"
rm $SERVER_REQ_FILE

echo "Done"
